### ISSUE TITLE
Cannot decode values larger than max int

### ISSUE THREAD

**Issue by yissachar** [peet/hashids.java#2]
```
Hashids hashids = new Hashids("some salt");
System.out.println(hashids.decrypt(hashids.encrypt(2147483647L)).length); // 1
System.out.println(hashids.decrypt(hashids.encrypt(2147483648L)).length); // 0
```

Encoding seems to work fine.

Based on the README this doesn't seem to be by design.

**Comment by yissachar** [comment]
The problem seems to lie in the unhash function. It is supposed to return a long but the internal numbers used are ints. Replacing it with the following corrects the issue:

```
private long unhash(String hash, String alphabet) {
    long number = 0;

    for (int i = 0; i < hash.length(); i++) {
      int pos = alphabet.indexOf(hash.charAt(i));
      number += pos * (long) Math.pow(alphabet.length(), hash.length() - i - 1);
    }

    return number;
  }
```

Both the declaration of number and the cast have been changed from int to long.

**Comment by manikantag** [comment]
+1 for the fix. This seems to be working. I've tested with different incremental random values looped 1 million times. Tests passing all the times.

**Comment by manikantag** [comment]
@peet Do you mind fixing this?

**Comment by yissachar** [comment]
I've opened a PR for convenience: https://github.com/peet/hashids.java/pull/5

**Comment by manikantag** [comment]
Great, thanks :) It's upto @peet now!

**Comment by yissachar** [comment]
Fixed by https://github.com/peet/hashids.java/pull/5
